### ISSUE TITLE
UndefinedTable: relation "creators_location" does not exist

### ISSUE THREAD

**Issue by Ndacyayisenga-droid** [unstructuredstudio/zubhub#728]
## psycopg2.errors.UndefinedTable: relation "creators_location" does not exist

The `zubhub_backend-web` docker image keeps [failing/restarting](https://github.com/unstructuredstudio/zubhub/blob/4420b0a3f83c4b006ae62ca1db5e12cd4ac1f267/zubhub_backend/docker-compose.yml#L10) seemingly due to   UndefinedTable: relation "creators_location".

Courtesy of the logs below

```
2023-08-29 22:42:33 
2023-08-29 22:42:33 0 static files copied to '/zubhub_backend/zubhub/staticfiles', 288 unmodified.
2023-08-29 22:42:34 Cache table 'default_cache_table' already exists.
2023-08-29 22:42:35 Traceback (most recent call last):
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-08-29 22:42:35     return self.cursor.execute(sql, params)
2023-08-29 22:42:35 psycopg2.errors.UndefinedTable: relation "creators_location" does not exist
2023-08-29 22:42:35 LINE 1: SELECT COUNT(*) AS "__count" FROM "creators_location"
2023-08-29 22:42:35                                           ^
2023-08-29 22:42:35 
2023-08-29 22:42:35 
2023-08-29 22:42:35 The above exception was the direct cause of the following exception:
2023-08-29 22:42:35 
2023-08-29 22:42:35 Traceback (most recent call last):
2023-08-29 22:42:35   File "/zubhub_backend/zubhub/manage.py", line 21, in <module>
2023-08-29 22:42:35     main()
2023-08-29 22:42:35   File "/zubhub_backend/zubhub/manage.py", line 17, in main
2023-08-29 22:42:35     execute_from_command_line(sys.argv)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
2023-08-29 22:42:35     utility.execute()
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
2023-08-29 22:42:35     self.fetch_command(subcommand).run_from_argv(self.argv)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
2023-08-29 22:42:35     self.execute(*args, **cmd_options)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
2023-08-29 22:42:35     output = self.handle(*args, **options)
2023-08-29 22:42:35   File "/zubhub_backend/zubhub/creators/management/commands/populate_countries.py", line 11, in handle
2023-08-29 22:42:35     if Location.objects.all().count() < 1:
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 412, in count
2023-08-29 22:42:35     return self.query.get_count(using=self.db)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 526, in get_count
2023-08-29 22:42:35     number = obj.get_aggregation(using, ['__count'])['__count']
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 511, in get_aggregation
2023-08-29 22:42:35     result = compiler.execute_sql(SINGLE)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
2023-08-29 22:42:35     cursor.execute(sql, params)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
2023-08-29 22:42:35     return super().execute(sql, params)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
2023-08-29 22:42:35     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2023-08-29 22:42:35     return executor(sql, params, many, context)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-08-29 22:42:35     return self.cursor.execute(sql, params)
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
2023-08-29 22:42:35     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-08-29 22:42:35   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-08-29 22:42:35     return self.cursor.execute(sql, params)
2023-08-29 22:42:35 django.db.utils.ProgrammingError: relation "creators_location" does not exist
2023-08-29 22:42:35 LINE 1: SELECT COUNT(*) AS "__count" FROM "creators_location"
2023-08-29 22:42:35                                           ^
2023-08-29 22:42:35 
```

<img width="1275" alt="Screenshot 1402-06-06 at 03 07 32" src="https://github.com/unstructuredstudio/zubhub/assets/58124613/d26f2626-0c46-4c0c-8a42-81737e475106">

**Comment by Formasitchijoh** [comment]
hello @Ndacyayisenga-droid  i ran into this same error and i solved it by running the command    
###  $ docker-compose up
 as specified in the installation guide then the
### $ make init 
I think the error was because the docker engine was not yet properly set so the containers were not spinning to complete the backend migrations,

**Comment by Ndacyayisenga-droid** [comment]
Actually I deleted the backend docker containers and ran `make init` again and that solved my issue
